# tools/project_info_tool.py
from enum import Enum
from pydantic import BaseModel, Field
from langchain_core.tools import tool

# Define an Enum for valid status values
class StatusEnum(str, Enum):
    operational = "Operational"
    offline_under_repair = "Offline/under repair"
    under_construction = "Under construction"
    contracted = "Contracted"
    announced = "Announced"
    announced_never_built = "Announced/never built"
    decommissioned = "Decommissioned"

# Define the Pydantic model with required fields only
class ProjectInfoSchema(BaseModel):
    project_name: str = Field(..., description="The name of the energy storage project/plant.")
    rated_power: float = Field(..., description="This is the rated power (specified in KW, convert if necessary) of the energy storage project/plant including all the subsystems.")
    storage_capacity: float = Field(..., description="This is storage capacity of the energy storage project/plant (specified in kWh convert if necessary). This may sometimes be referred to as the energy capacity of the energy storage project/plant including all the subsystems.")
    discharge_duration: float = Field(None, description="This refers to the length of time an energy storage project/plant can deliver power at its rated power output before its energy capacity is depleted.")
    paired_grid_resources: str = Field(None, description="Other grid resources paired with the plant. The energy storage project/plant may be paired with other grid resources to provide numerous benefits to the electrical grid. Some examples of paired grid resources are: renewable energy resources like wind or solar, peaker plants, diesel generators, microgrids, electric vehicle charging stations.")
    status: StatusEnum = Field(..., description="Current status of the energy storage project/plant. Valid values for this field are: Operational; Offline/under repair; Under construction; Contracted; Announced; Announced/never built; Decommissioned.")
    url: str = Field(None, description="The URL providing additional information about the project.")
    description_notes: str = Field(None, description="Any additional description or notes about the project.")

@tool
def extract_project_info(project_info: ProjectInfoSchema):
    """
    Extracts key project information, including:

    - Project Name: Name of the energy storage project or plant.
    - Rated Power: Project’s rated power in kW.
    - Storage Capacity: Energy storage capacity in kWh.
    - Discharge Duration: Duration (in hours) for rated output.
    - Paired Grid Resources: Resources paired with the project (e.g., wind, solar).
    - Status: Current operational status (e.g., Operational, Offline).
    - URL: Source of the provided text.
    - Description/Notes: Brief project description generated by the tool.
    """

    return (
        f"project_name: {project_info.project_name}, "
        f"Rated Power (kW): {project_info.rated_power}, "
        f"Storage Capacity (kWh): {project_info.storage_capacity}, "
        f"Discharge Duration at Rated Power (hrs): {project_info.discharge_duration or None}, "
        f"Paired Grid Resources: {project_info.paired_grid_resources or None}, "
        f"Status: {project_info.status}, "
        f"URL: {project_info.url or None}, "
        f"Description/Notes: {project_info.description_notes or None}"
    )
