"""Short descriptions for search queries and LLM extraction, aligned with extractor tools."""
# Map: GESDB field name (as in record) -> description for search + LLM
FIELD_DESCRIPTIONS = {
    "Project/Plant Name": "Name of the energy storage project or plant.",
    "Status": "Current status: Operational, Under construction, Announced, Contracted, Decommissioned, etc.",
    "Rated Power (kW)": "Rated power in kW of the energy storage project/plant.",
    "Storage Capacity (kWh)": "Storage capacity in kWh (energy capacity) of the project/plant.",
    "Discharge Duration at Rated Power (hrs)": "Hours the plant can deliver power at rated output before capacity is depleted.",
    "Paired Grid Resources": "Grid resources paired with the plant (e.g. wind, solar, peaker plants).",
    "Description/Notes": "Brief description or notes about the project.",
    "URL": "URL with more information about the project.",
    "Latest Update Date": "Date of latest update (MM-DD-YYYY).",
    "Country": "Country where the project is located.",
    "City": "City where the project is located.",
    "State/Province": "State or province where the project is located.",
    "State/Province/Territory": "State, province or territory where the project is located.",
    "County": "County (e.g. US) where the project is located.",
    "Street Address": "Street address of the project.",
    "Postal Code": "Postal code of the location.",
    "Latitude": "Latitude in signed degrees.",
    "Longitude": "Longitude in signed degrees.",
    "Announced Date": "Date the project was announced (MM-DD-YYYY).",
    "Constructed Date": "Date construction was completed (MM-DD-YYYY).",
    "Commissioned Date": "Date the project was commissioned (MM-DD-YYYY).",
    "Decommissioned Date": "Date decommissioned or N/A (MM-DD-YYYY).",
    "Contact Information: Name": "Project contact person full name.",
    "Contact Information: Email Address": "Project contact email address.",
    "Contact Information: Phone Number": "Project contact phone number.",
    "Grid Interconnection Level": "Transmission, Distribution, or Customer (behind-the-meter).",
    "Interconnection Type": "AC, DC, or Hybrid.",
    "ISO/RTO": "Independent System Operator or Regional Transmission Organization.",
    "System Operator": "Entity that operates the system.",
    "Utility Type": "Investor Owned, Public-owned, Cooperative, State/municipal-owned, Federally-owned.",
    "Ownership Model": "Utility-Owned, Customer-owned, or Other.",
    "Owner(s)": "List of owners of the project.",
    "Capital Expenditure - CAPEX (USD)": "Capital expenditure in USD.",
    "Captial Expenditure - CAPEX (USD)": "Capital expenditure in USD.",
    "Annual Operational Cost - OPEX (USD)": "Annual operational cost in USD.",
    "Debt Provider": "Debt provider for the project.",
    "Funding Source 1": "Primary funding source.",
    "Funding Source Amount 1 (USD)": "Amount from primary funding source in USD.",
    "Funding Source 2": "Secondary funding source.",
    "Funding Source Amount 2 (USD)": "Amount from secondary funding source in USD.",
    "Funding Source 3": "Tertiary funding source.",
    "Funding Source Amount 3 (USD)": "Amount from tertiary funding source in USD.",
    # Subsystem (Storage Device, PCS, BoS)
    "Storage Capacity (kWh)": "Storage capacity in kWh.",
    "Round-trip Efficiency (%)": "Round-trip efficiency percentage.",
    "Depth of Discharge (%)": "Depth of discharge percentage.",
    "Rated Power (kW)": "Rated power in kW.",
    "Maximum Charge Power (kW)": "Maximum charge power in kW.",
    "Maximum Discharge Power (kW)": "Maximum discharge power in kW.",
    "Full Load Efficiency (%)": "Full load efficiency percentage.",
    "Transformer Rating": "Transformer rating (e.g. kW or MVA).",
    "Transformer Configuration": "Transformer configuration (e.g. two-winding).",
    "Controller Type": "Controller type (e.g. Opticaster, Egility).",
}


def get_descriptions_for_fields(field_names: list[str]) -> dict[str, str]:
    return {f: FIELD_DESCRIPTIONS.get(f, f) for f in field_names}
