'''Consumes validation data generated by the validation script. At the moment,
it counts the occurrence of specific errorcodes.'''

import json
import pandas as pd

# ***** Read the output data after running validation script
validation_results = pd.read_json(r'validation/output/validation_status.json')
gesdb_fields = list(validation_results.keys())
gesdb_fields.pop(0)  # -Remove field 'Index'

# ***** Create a pandas dataframe to store all the error Count
df_error_count_cols = ['Error Code 101', 'Error Code 102', 'Error Code 103',
                       'Error Code 104', 'Error Code 105', 'Error Code 106',
                       'Error Code 107', 'Error Code 108', 'Error Code 201',
                       'Error Code 202', 'Error Code 203', 'Error Code 204',
                       'Error Code 205', 'Error Code 206']
df_error_count = pd.DataFrame(columns=df_error_count_cols)

# - Count number of data points in the database
num_data_points = validation_results['ID'].count()
# num_data_points = 5

for row in range(num_data_points):
    # - Reset all counters to 0 for each new data
    CTR_101_ERROR = 0
    CTR_102_ERROR = 0
    CTR_103_ERROR = 0
    CTR_104_ERROR = 0
    CTR_105_ERROR = 0
    CTR_106_ERROR = 0
    CTR_107_ERROR = 0
    CTR_108_ERROR = 0

    CTR_201_ERROR = 0
    CTR_202_ERROR = 0
    CTR_203_ERROR = 0
    CTR_204_ERROR = 0
    CTR_205_ERROR = 0
    CTR_206_ERROR = 0

    for field in gesdb_fields:
        # - extract the error code of all fields
        error_code = validation_results[field][row][0]['error_codes']
        # - check if an error code was returned

        if error_code:
            error_code_list = [int(x) for x in error_code.split(',')]
            # - Error counting
            for ctr, _ in enumerate(error_code_list):
                # - Count 1XX type errors
                if error_code_list[ctr] == 101:
                    CTR_101_ERROR += 1
                elif error_code_list[ctr] == 102:
                    CTR_102_ERROR += 1
                elif error_code_list[ctr] == 103:
                    CTR_103_ERROR += 1
                elif error_code_list[ctr] == 104:
                    CTR_104_ERROR += 1
                elif error_code_list[ctr] == 105:
                    CTR_105_ERROR += 1
                elif error_code_list[ctr] == 106:
                    CTR_106_ERROR += 1
                elif error_code_list[ctr] == 107:
                    CTR_107_ERROR += 1
                elif error_code_list[ctr] == 108:
                    CTR_108_ERROR += 1
                # - Count 2XX type errors
                if error_code_list[ctr] == 201:
                    CTR_201_ERROR += 1
                elif error_code_list[ctr] == 202:
                    CTR_202_ERROR += 1
                elif error_code_list[ctr] == 203:
                    CTR_203_ERROR += 1
                elif error_code_list[ctr] == 204:
                    CTR_204_ERROR += 1
                elif error_code_list[ctr] == 205:
                    CTR_205_ERROR += 1
                elif error_code_list[ctr] == 206:
                    CTR_206_ERROR += 1

    # - Store error count to a pandas dataframe
    df_error_count.loc[row, :] = [CTR_101_ERROR, CTR_102_ERROR, CTR_103_ERROR,
                                  CTR_104_ERROR, CTR_105_ERROR, CTR_106_ERROR,
                                  CTR_107_ERROR, CTR_108_ERROR, CTR_201_ERROR,
                                  CTR_202_ERROR, CTR_203_ERROR, CTR_204_ERROR,
                                  CTR_205_ERROR, CTR_206_ERROR]

# ***** Write the error count to a CSV file
df_error_count.to_csv(r'output/error_count.csv')
